name: AIOps CI

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          pip install -r requirements.txt

      - name: Frontend Build
        run: |
          docker build -f docker/Dockerfile.frontend -t frontend .

      - name: Backend Build
        run: |
          docker build -f docker/Dockerfile.backend -t backend .